/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package browser;

import browser.image.histryfield;
import static jdk.nashorn.internal.objects.NativeArray.length;

/**
 *
 * @author User
 */
public class browserr extends javax.swing.JFrame {

    /**
     * Creates new form browserr
     */
    public browserr() {
        initComponents();
    }

    /*  private void initialize() {

     setting.addItem("A");
     setting.addItem("B");
     setting.addItem("C");
     } */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        searchh = new javax.swing.JButton();
        bsmrstu = new javax.swing.JButton();
        facebook = new javax.swing.JButton();
        youtube = new javax.swing.JButton();
        google = new javax.swing.JButton();
        gmail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newtap = new javax.swing.JMenuItem();
        histry = new javax.swing.JMenuItem();
        setting = new javax.swing.JMenu();
        signin = new javax.swing.JMenuItem();
        them = new javax.swing.JMenuItem();
        help = new javax.swing.JMenuItem();
        develop = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        display.setBackground(new java.awt.Color(255, 255, 255));
        display.setLayout(null);

        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setBorder(null);
        display.add(search);
        search.setBounds(280, 290, 450, 40);

        searchh.setBackground(new java.awt.Color(255, 255, 255));
        searchh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchh.setForeground(new java.awt.Color(255, 0, 0));
        searchh.setText("search");
        searchh.setBorder(null);
        searchh.setBorderPainted(false);
        searchh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchhActionPerformed(evt);
            }
        });
        display.add(searchh);
        searchh.setBounds(750, 290, 110, 40);

        bsmrstu.setIcon(new javax.swing.ImageIcon("G:\\java photo\\bsmrstu.jpg")); // NOI18N
        bsmrstu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bsmrstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsmrstuActionPerformed(evt);
            }
        });
        display.add(bsmrstu);
        bsmrstu.setBounds(790, 380, 130, 120);

        facebook.setIcon(new javax.swing.ImageIcon("G:\\java photo\\fb.png")); // NOI18N
        facebook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        facebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookActionPerformed(evt);
            }
        });
        display.add(facebook);
        facebook.setBounds(190, 380, 130, 120);

        youtube.setIcon(new javax.swing.ImageIcon("G:\\java photo\\youtube.png")); // NOI18N
        youtube.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        youtube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youtubeActionPerformed(evt);
            }
        });
        display.add(youtube);
        youtube.setBounds(340, 380, 130, 120);

        google.setIcon(new javax.swing.ImageIcon("G:\\java photo\\google.png")); // NOI18N
        google.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        google.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                googleActionPerformed(evt);
            }
        });
        display.add(google);
        google.setBounds(490, 380, 130, 120);

        gmail.setIcon(new javax.swing.ImageIcon("G:\\java photo\\gmail.jpg")); // NOI18N
        gmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmailActionPerformed(evt);
            }
        });
        display.add(gmail);
        gmail.setBounds(640, 380, 130, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/browser/image/AppListIcon.scale-100.png"))); // NOI18N
        display.add(jLabel1);
        jLabel1.setBounds(210, 290, 50, 40);
        display.add(jSeparator1);
        jSeparator1.setBounds(280, 330, 450, 2);

        jMenu1.setText(":::::");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        newtap.setText("New Tap");
        newtap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtapActionPerformed(evt);
            }
        });
        jMenu1.add(newtap);

        histry.setText("History");
        histry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histryActionPerformed(evt);
            }
        });
        jMenu1.add(histry);

        setting.setText("Setting");

        signin.setText("Sign in");
        setting.add(signin);

        them.setText("theme");
        setting.add(them);

        jMenu1.add(setting);

        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jMenu1.add(help);

        develop.setText("Developer");
        develop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                developActionPerformed(evt);
            }
        });
        jMenu1.add(develop);

        exit.setText("Exit Browser");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsmrstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsmrstuActionPerformed
        page Info = new page();
        try {
            page.display.setPage("https://www.bsmrstu.edu.bd/b/");
            page.linkshow.setText("https://www.bsmrstu.edu.bd/b/");
            Info.setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_bsmrstuActionPerformed

    private void facebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookActionPerformed
        page Info = new page();
        try {
            page.display.setPage("https://www.facebook.com/");
            page.linkshow.setText("https://www.facebook.com/");
            Info.setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_facebookActionPerformed

    private void youtubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youtubeActionPerformed
        page Info = new page();
        try {
            page.display.setPage("https://www.youtube.com/");
            page.linkshow.setText("https://www.youtube.com/");
            Info.setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_youtubeActionPerformed

    private void googleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_googleActionPerformed
        page Info = new page();
        try {
            page.display.setPage("https://www.google.com/");
            page.linkshow.setText("https://www.google.com/");
            Info.setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_googleActionPerformed

    private void gmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmailActionPerformed
        page Info = new page();
        try {
            page.display.setPage("https://www.gmail.com/");

            page.linkshow.setText("https://www.gmail.com/");

            Info.setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_gmailActionPerformed

    private void searchhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchhActionPerformed
        // String link = "http://www." + search.getText() + ".com";
        String link = search.getText();
        if (link.length() > 16) {
            //System.out.print(link);
            page Info = new page();
            try {
                page.display.setPage(link);
                page.linkshow.setText(link);
                //histryfield.linkfield.setText(link);
                Info.setVisible(true);
            } catch (Exception e) {

            }
        } else {
            link = "http://www." + link + ".com";
            page Info = new page();
            try {
                page.display.setPage(link);
                page.linkshow.setText(link);
                Info.setVisible(true);
            } catch (Exception e) {

            }
        }
        /* String link = search.getText().replace(" ", "");
         try {
         java.awt.Desktop.getDesktop().browse(java.net.URI.create("http://www.google.com/search?h1=en&q=" + link + "&btnG=Google+Search"));
         } catch (Exception e) {

         }  */
    }//GEN-LAST:event_searchhActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void newtapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtapActionPerformed
        browserr bellal = new browserr();
        bellal.setVisible(true);
    }//GEN-LAST:event_newtapActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void histryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histryActionPerformed
        histryfield bellal = new histryfield();
        display.add(bellal);
        bellal.setVisible(true);
    }//GEN-LAST:event_histryActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        help bellal = new help();
        bellal.setVisible(true);
    }//GEN-LAST:event_helpActionPerformed

    private void developActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_developActionPerformed
        developer bellal = new developer();
        bellal.setVisible(true);
    }//GEN-LAST:event_developActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(browserr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(browserr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(browserr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(browserr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new browserr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsmrstu;
    private javax.swing.JMenuItem develop;
    private javax.swing.JPanel display;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton facebook;
    private javax.swing.JButton gmail;
    private javax.swing.JButton google;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenuItem histry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem newtap;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchh;
    private javax.swing.JMenu setting;
    private javax.swing.JMenuItem signin;
    private javax.swing.JMenuItem them;
    private javax.swing.JButton youtube;
    // End of variables declaration//GEN-END:variables

    private boolean leangth(String link) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
